version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: "mysql_sub_service"
    restart: always
    environment:
      MYSQL_DATABASE: submission_service
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
